nelmio_api_doc:
    documentation:
        info:
            title: Api CMS
            description: Api CMS Symfony
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/core # Accepts routes under /api except /api/doc
